### ISSUE TITLE
Use flatbuffers

### ISSUE THREAD

**Issue by zeroqn** [cryptape/muta#14]
Replace protobuf.
0 additional allocations and faster than protobuf.
@yejiayu

**Comment by u2** [comment]
https://github.com/nervosnetwork/rfcs/pull/47/files

**Comment by zeroqn** [comment]
https://google.github.io/flatbuffers/flatbuffers_support.html

**Comment by yangby-cryptape** [comment]
Since we have different opinions, I think we could write an abstract serialization crate:
- Users only can use the methods provided by the abstract serialization crate.
- The inner methods of the specific serialization crate (flatbuffer or protobuf) should not be used directly.

So, if anyone want to replace the serialization crate, it will be easy.

**Comment by yejiayu** [comment]
> Since we have different opinions, I think we could write an abstract serialization crate:
> 
> * Users only can use the methods provided by the abstract serialization crate.
> * The inner methods of the specific serialization crate (flatbuffer or protobuf) should not be used directly.
> 
> So, if anyone want to replace the serialization crate, it will be easy.

Cool but i don’t think it is necessary at present.

**Comment by yangby-cryptape** [comment]
> Cool but i don’t think it is necessary at present.

It is easy than you think, if you do it at beginning.
And, it will be very hard if you do it after coding a lot.

**It's easy to lose sight of what you want, especially if you haven't gotten it.**

Now, in CITA, no crates use protobuf methods directly, except `libproto`.
Check this [`Cargo.lock`], please.

[`Cargo.lock`]: https://github.com/cryptape/cita/blob/de7bbcb1b5746dcabd5954fea67fa8edf2e84e49/Cargo.lock

**Comment by zeroqn** [comment]
I can try to port benchmarks from quick-protobuf to flatbuffers.
