### ISSUE TITLE
Rather Arcane Code

### ISSUE THREAD

**Issue by yangby-cryptape** [cryptape/muta#18]
All import things are list as follow:
https://github.com/cryptape/muta/blob/ae157e29443fd90b5375e83e30bf5f39d14787ac/examples/monolith-chain/src/pool.rs#L1-L6

So, can you guess what is the follow `Result` (a tip: do not be confused, it is not [`std:result::Result`])?
https://github.com/cryptape/muta/blob/ae157e29443fd90b5375e83e30bf5f39d14787ac/examples/monolith-chain/src/pool.rs#L24-L30

Surprise! It is [`proto::common::Result`]!

>   --> examples/monolith-chain/src/pool.rs:18:23
>    |
> 18 |         let mut ret = Result::new();
>    |                       ^^^^^^^^^^^ variant not found in `std::result::Result<_, _>`

[`std:result::Result`]: https://doc.rust-lang.org/std/result/enum.Result.html
[`proto::common::Result`]: https://github.com/cryptape/muta/blob/ae157e29443fd90b5375e83e30bf5f39d14787ac/proto/proto/common.proto#L5-L8

**Comment by zeroqn** [comment]
Indeed bad smell here.
I also don't like common::Result. Still thinking a more comfortable name for those return values.
Any suggestions?

**Comment by yangby-cryptape** [comment]
> Indeed bad smell here.
> I also don't like common::Result. Still trying to figure out a more comfortable name for those return values.
> Any suggestions?

I think `namespace` was designed for the scenes like this: classify items which have same name but in the different modules.

I disapprove almost all `*` in `import` sections.

**Comment by zeroqn** [comment]
> 
> I think `namespace` was designed for the scenes like this: classify items which have same name but in the different modules.
> 
I mean most of structs don't have `namespace` prefix, but only `common::Result`.

>
> I disapprove almost all `*` in `import` sections.
>
Agree. But for some frequently used structs, i think it's ok to `re-export` them in `prelude`.
I tried to make `prelude` very small.

**Comment by yangby-cryptape** [comment]
> Agree. But for some frequently used structs, i think it's ok to `re-export` them in `prelude`.
> I tried to make `prelude` very small.

If you `import` more than one `*` in one file, it also confuse all reviewers and readers.
Where are the items imported from?
IMHO, no `*` should be allowed in `import` sections.

**Comment by zeroqn** [comment]
> If you `import` more than one `*` in one file, it also confuse all reviewers and readers, even each `prelude` has only **one** item.
> Where is the item imported from?
> IMHO, no `*` should be allowed in `import` sections.

I think a proper prefix may fix this problem. For example, ```pub use Context as MutaProtocolContext```.

**Comment by yangby-cryptape** [comment]
+ A
    ```rust
    use muta::prelude::*;
    use muta_proto::prelude::*;

    fn f() {
       let _ = MutaProtocolContext::new();
    }
    ```
+ B

    ```rust
    use muta::protocol;
    use muta_proto;

    fn f() {
       let _ = protocol::Context::new();
    }
    ```

B is more clear and B has less characters.

Since there has `namespace`, why use a **complex name**?

**Comment by zeroqn** [comment]
Agree
